services:
  db:
    image: postgres:15
    container_name: trade_wasted_food-db
    volumes:
      - db_data:/var/lib/postgresql/data  # DBデータの永続化のためのボリューム
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # .env から読み込む
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # .env から読み込む
      POSTGRES_DB: ${POSTGRES_DB}  # .env から読み込む
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app  # ソースコードの同期
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      UPSTASH_REDIS_URL: ${UPSTASH_REDIS_URL}
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_ENV: "development"
    ports:
      - "3000:3000"
    command:
      bin/rails server -b '0.0.0.0' -p 3000  # bin/railsを使ってHTTPで起動


  redis:
    image: redis:latest
    container_name: trade_wasted_food-redis
    ports:
      - "6379:6379"

volumes:
  db_data:  # データボリュームの設定
