version: '3.9'

services:
  db:
    image: postgres:15
    container_name: trade_wasted_food-db
    volumes:
      - db_data:/var/lib/postgresql/data  # DBデータの永続化のためのボリューム
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # .env から読み込む
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # .env から読み込む
      POSTGRES_DB: ${POSTGRES_DB}  # .env から読み込む
    ports:
      - "5432:5432"

  web:
    build: .  # コンテナビルド用の設定
    depends_on:
      - db  # DBが起動するのを待つ
    volumes:
      - .:/app  # ホストとコンテナの間でソースコードを同期
    environment:
      DATABASE_URL: ${DATABASE_URL}  # .env から読み込む
      REDIS_URL: ${REDIS_URL}  # .env から読み込む
    ports:
      - "3000:3000"

  redis:
    image: redis:latest
    container_name: trade_wasted_food-redis
    ports:
      - "6379:6379"

volumes:
  db_data:  # データボリュームの設定
