version: '3.9'

services:
  db:
    image: postgres:15
    container_name: trade_wasted_food-db
    volumes:
      - db_data:/var/lib/postgresql/data  # DBデータの永続化のためのボリューム
    environment:
      POSTGRES_USER: trade_wasted_food
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trade_wasted_food
    ports:
      - "5432:5432"

  web:
    build: .  # コンテナビルド用の設定
    depends_on:
      - db  # DBが起動するのを待つ
    volumes:
      - .:/app  # ホストとコンテナの間でソースコードを同期
    environment:
      POSTGRES_USER: trade_wasted_food
      POSTGRES_PASSWORD: password
      DATABASE_URL: postgres://trade_wasted_food:password@db/trade_wasted_food_development
    ports:
      - "3000:3000"

volumes:
  db_data:  # データボリュームの設定
