version: '3.9'

services:
  db:
    image: postgres:15
    container_name: trade_wasted_food-db
    volumes:
      - db_data:/var/lib/postgresql/data  # ボリュームを変更
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trade_wasted_food
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: trade_wasted_food-web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/trade_wasted_food
    volumes:
      - .:/trade_wasted_food

volumes:
  db_data:
