default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>  # DATABASE_URL を使うように変更

development:
  <<: *default
  database: trade_wasted_food
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

test:
  <<: *default
  database: trade_wasted_food_test
  url: <%= ENV['DATABASE_URL_TEST'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
  username: trade_wasted_food
  password: <%= ENV["TRADE_WASTED_FOOD_DATABASE_PASSWORD"] %>