default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: trade_wasted_food_development
  username: trade_wasted_food
  password: password

test:
  <<: *default
  database: trade_wasted_food_test

production:
  <<: *default
  database: trade_wasted_food_production
  username: trade_wasted_food
  password: <%= ENV["TRADE_WASTED_FOOD_DATABASE_PASSWORD"] %>