default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>  # DATABASE_URL を使うように変更

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> 

test:
  <<: *default
  database: trade_wasted_food_test
  url: <%= ENV['DATABASE_URL_TEST'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>  # database: を url: に変更
  username: trade_wasted_food
  password: <%= ENV["TRADE_WASTED_FOOD_DATABASE_PASSWORD"] %>